// Mock product data for the stationery store.

import type { Product } from "@/lib/types/product";

export type { Product };

export const allProducts: Product[] = [
  {
    id: "fp-001",
    slug: "midnight-velvet-journal",
    name: "Midnight Velvet Journal",
    category: "Notebooks",
    categorySlug: "notebooks",
    price: 1250,
    originalPrice: 1500,
    discount: 17,
    image: "https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=400&h=400&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1589582754973-0d6a8d4ab790?w=800&h=800&fit=crop",
    ],
    description:
      "A premium hardbound journal with a luxurious velvet-touch cover in deep midnight blue. Contains 192 pages of 100gsm acid-free paper, perfect for fountain pens and ink.",
    badge: "bestseller",
    isFeatured: true,
    tags: ["premium"],
    rating: 4.8,
    reviewCount: 234,
    inStock: true,
    brand: "Inkwell Original",
    sku: "INK-NB-001",
    unit: "Piece",
    stock: 45,
  },
  {
    id: "fp-002",
    slug: "sakura-brush-pen-set",
    name: "Sakura Brush Pen Set (12pc)",
    category: "Pens",
    categorySlug: "pens",
    price: 1890,
    image: "https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=400&h=400&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=800&h=800&fit=crop",
    ],
    description:
      "Professional-grade brush pens with flexible nylon tips that mimic natural calligraphy strokes. Water-based ink, archival quality, and fade-resistant.",
    badge: "new",
    isFeatured: true,
    tags: ["art", "premium"],
    rating: 4.9,
    reviewCount: 89,
    inStock: true,
    brand: "Sakura Art",
    sku: "SAK-PN-012",
    unit: "Set",
    stock: 8,
  },
  {
    id: "fp-003",
    slug: "kraft-paper-wrap-roll",
    name: "Kraft Paper Wrap Roll",
    category: "Paper",
    categorySlug: "paper",
    price: 450,
    image: "https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&h=400&fit=crop",
    description:
      "Natural brown kraft paper roll, 30cm wide x 10 meters. Ideal for gift wrapping, crafts, and packaging. Recyclable and biodegradable.",
    isFeatured: true,
    tags: ["minimal"],
    rating: 4.5,
    reviewCount: 56,
    inStock: true,
    brand: "Inkwell Original",
    sku: "INK-PP-003",
    unit: "Roll",
    stock: 120,
  },
  {
    id: "fp-004",
    slug: "desk-organizer-bamboo-set",
    name: "Desk Organizer Bamboo Set",
    category: "Office Supplies",
    categorySlug: "office-supplies",
    price: 2200,
    originalPrice: 2800,
    discount: 21,
    image: "https://images.unsplash.com/photo-1589582754973-0d6a8d4ab790?w=400&h=400&fit=crop",
    description:
      "Handcrafted bamboo desk organizer with 5 compartments. Eco-friendly material with a natural grain finish. Dimensions: 25 x 10 x 12 cm.",
    badge: "sale",
    isFeatured: true,
    tags: ["office", "premium"],
    rating: 4.7,
    reviewCount: 178,
    inStock: true,
    brand: "Inkwell Original",
    sku: "INK-OS-004",
    unit: "Set",
    stock: 3,
  },
  {
    id: "fp-005",
    slug: "watercolor-pan-palette",
    name: "Watercolor Pan Palette (24 Colors)",
    category: "Art Supplies",
    categorySlug: "art-supplies",
    price: 3200,
    image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&h=400&fit=crop",
    description:
      "Artist-grade watercolor pan set with 24 vivid, lightfast colors in a compact metal tin. Each half-pan is refillable.",
    badge: "new",
    isFeatured: true,
    tags: ["art", "colorful"],
    rating: 4.6,
    reviewCount: 42,
    inStock: true,
    brand: "ArtLine Pro",
    sku: "ALP-AS-024",
    unit: "Set",
    stock: 22,
  },
  {
    id: "fp-006",
    slug: "premium-gel-ink-pens",
    name: "Premium Gel Ink Pens (8pc)",
    category: "Pens",
    categorySlug: "pens",
    price: 680,
    originalPrice: 850,
    discount: 20,
    image: "https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=400&h=400&fit=crop",
    description:
      "Smooth-writing 0.7mm gel ink pens in 8 vibrant colors. Quick-dry formula resists smudging. Ideal for notes, journaling, and color-coding.",
    badge: "bestseller",
    isFeatured: true,
    tags: ["colorful", "premium"],
    rating: 4.4,
    reviewCount: 312,
    inStock: true,
    brand: "Inkwell Original",
    sku: "INK-PN-008",
    unit: "Set",
    stock: 65,
  },
  {
    id: "bsw-001",
    slug: "college-ruled-spiral-notebook",
    name: "College Ruled Spiral Notebook",
    category: "Notebooks",
    categorySlug: "notebooks",
    price: 350,
    image: "https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=400&h=400&fit=crop",
    description:
      "Standard A4 spiral notebook with 200 pages of college-ruled paper. Durable plastic cover and twin-wire binding.",
    badge: "bestseller",
    tags: ["student"],
    rating: 4.7,
    reviewCount: 891,
    inStock: true,
    brand: "Inkwell Original",
    sku: "INK-NB-010",
    unit: "Piece",
    stock: 200,
  },
  {
    id: "bsw-002",
    slug: "sticky-note-pack",
    name: "Sticky Note Pack (6 colors)",
    category: "Office Supplies",
    categorySlug: "office-supplies",
    price: 220,
    image: "https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=400&h=400&fit=crop",
    description:
      "Pack of 6 bright neon sticky notes, 100 sheets each. Repositionable adhesive leaves no residue.",
    rating: 4.3,
    reviewCount: 445,
    inStock: true,
    tags: ["office", "colorful"],
    brand: "Inkwell Original",
    sku: "INK-OS-020",
    unit: "Pack",
    stock: 150,
  },
  {
    id: "bsw-003",
    slug: "fine-liner-drawing-pens",
    name: "Fine Liner Drawing Pens",
    category: "Pens",
    categorySlug: "pens",
    price: 550,
    image: "https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=400&h=400&fit=crop",
    description:
      "Precision-tip fine liner pens in 4 sizes. Waterproof pigment ink for technical drawing, sketching, and illustration.",
    badge: "bestseller",
    tags: ["art", "minimal"],
    rating: 4.6,
    reviewCount: 678,
    inStock: true,
    brand: "ArtLine Pro",
    sku: "ALP-PN-004",
    unit: "Set",
    stock: 95,
  },
  {
    id: "bsw-004",
    slug: "a4-copy-paper",
    name: "A4 Copy Paper (500 sheets)",
    category: "Paper",
    categorySlug: "paper",
    price: 380,
    image: "https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&h=400&fit=crop",
    description:
      "Standard A4 multipurpose copy paper, 80gsm. 500 sheets per ream. Suitable for inkjet and laser printing.",
    rating: 4.5,
    reviewCount: 1203,
    inStock: true,
    tags: ["student", "minimal"],
    brand: "Inkwell Original",
    sku: "INK-PP-040",
    unit: "Ream",
    stock: 300,
  },
  {
    id: "bsw-005",
    slug: "geometry-box-standard",
    name: "Geometry Box Standard",
    category: "School Essentials",
    categorySlug: "school-essentials",
    price: 420,
    image: "https://images.unsplash.com/photo-1589582754973-0d6a8d4ab790?w=400&h=400&fit=crop",
    description:
      "Complete geometry set including compass, divider, set squares, protractor, ruler, and pencil in a snap-shut case.",
    rating: 4.2,
    reviewCount: 567,
    inStock: true,
    tags: ["student"],
    brand: "Inkwell Original",
    sku: "INK-SE-005",
    unit: "Set",
    stock: 75,
  },
  {
    id: "bsw-006",
    slug: "wax-crayons-32-colors",
    name: "Wax Crayons (32 colors)",
    category: "Art Supplies",
    categorySlug: "art-supplies",
    price: 280,
    image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&h=400&fit=crop",
    description:
      "Non-toxic wax crayons in 32 rich colors. Smooth, even laydown with vibrant pigmentation. Safe for kids.",
    badge: "bestseller",
    tags: ["art", "colorful"],
    rating: 4.4,
    reviewCount: 892,
    inStock: true,
    brand: "Inkwell Original",
    sku: "INK-AS-032",
    unit: "Pack",
    stock: 0,
  },
  {
    id: "bsm-001",
    slug: "leather-bound-diary-2026",
    name: "Leather Bound Diary 2026",
    category: "Notebooks",
    categorySlug: "notebooks",
    price: 1800,
    image: "https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=400&h=400&fit=crop",
    description:
      "Full-year 2026 diary with genuine leather cover and ribbon bookmark. Weekly and monthly planning pages.",
    badge: "bestseller",
    tags: ["premium"],
    rating: 4.8,
    reviewCount: 2341,
    inStock: true,
    brand: "Inkwell Original",
    sku: "INK-NB-050",
    unit: "Piece",
    stock: 55,
  },
  {
    id: "bsm-002",
    slug: "calligraphy-starter-kit",
    name: "Calligraphy Starter Kit",
    category: "Pens",
    categorySlug: "pens",
    price: 1450,
    image: "https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=400&h=400&fit=crop",
    description:
      "Everything a beginner needs: 3 nib holders, 6 nibs, 2 bottles of ink, practice sheets, and a step-by-step guide.",
    rating: 4.7,
    reviewCount: 1876,
    inStock: true,
    tags: ["art", "premium"],
    brand: "ArtLine Pro",
    sku: "ALP-PN-050",
    unit: "Set",
    stock: 12,
  },
  {
    id: "bsm-003",
    slug: "sketch-book-a4",
    name: "Sketch Book A4 (200gsm)",
    category: "Art Supplies",
    categorySlug: "art-supplies",
    price: 650,
    image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&h=400&fit=crop",
    description:
      "Heavyweight 200gsm cartridge paper, ideal for pencil, charcoal, ink, and light washes. 80 sheets, A4 size.",
    badge: "bestseller",
    tags: ["art", "minimal"],
    rating: 4.6,
    reviewCount: 1543,
    inStock: true,
    brand: "ArtLine Pro",
    sku: "ALP-AS-050",
    unit: "Piece",
    stock: 40,
  },
  {
    id: "bsm-004",
    slug: "whiteboard-markers-12pc",
    name: "Whiteboard Markers (12pc)",
    category: "Office Supplies",
    categorySlug: "office-supplies",
    price: 480,
    image: "https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=400&h=400&fit=crop",
    description:
      "Low-odor dry-erase markers in 12 colors. Chisel tip for thick or thin lines. Easy-wipe formula leaves no ghosting.",
    rating: 4.3,
    reviewCount: 987,
    inStock: true,
    tags: ["office"],
    brand: "Inkwell Original",
    sku: "INK-OS-060",
    unit: "Set",
    stock: 85,
  },
  {
    id: "bsm-005",
    slug: "exercise-book-bundle",
    name: "Exercise Book Bundle (10pc)",
    category: "School Essentials",
    categorySlug: "school-essentials",
    price: 520,
    image: "https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&h=400&fit=crop",
    description:
      "Pack of 10 A5 exercise books, 40 pages each, ruled. Durable laminated cover in assorted colors.",
    badge: "bestseller",
    tags: ["student"],
    rating: 4.5,
    reviewCount: 2109,
    inStock: true,
    brand: "Inkwell Original",
    sku: "INK-SE-010",
    unit: "Pack",
    stock: 180,
  },
  {
    id: "bsm-006",
    slug: "origami-paper-pack",
    name: "Origami Paper Pack (200 sheets)",
    category: "Paper",
    categorySlug: "paper",
    price: 340,
    image: "https://images.unsplash.com/photo-1589582754973-0d6a8d4ab790?w=400&h=400&fit=crop",
    description:
      "200 sheets of colorful origami paper in 20 designs. 15cm x 15cm, single-sided printed with vibrant patterns.",
    rating: 4.4,
    reviewCount: 765,
    inStock: true,
    tags: ["art", "colorful"],
    brand: "Inkwell Original",
    sku: "INK-PP-060",
    unit: "Pack",
    stock: 110,
  },
  {
    id: "na-001",
    slug: "cloud-soft-eraser-set",
    name: "Cloud Soft Eraser Set",
    category: "School Essentials",
    categorySlug: "school-essentials",
    price: 180,
    image: "https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=400&h=400&fit=crop",
    description:
      "Ultra-soft cloud-shaped erasers that lift graphite cleanly without smudging. Set of 4 pastel colors.",
    badge: "new",
    tags: ["student", "minimal"],
    rating: 4.2,
    reviewCount: 18,
    inStock: true,
    brand: "Inkwell Original",
    sku: "INK-SE-018",
    unit: "Set",
    stock: 6,
  },
  {
    id: "na-002",
    slug: "vintage-typewriter-notebook",
    name: "Vintage Typewriter Notebook",
    category: "Notebooks",
    categorySlug: "notebooks",
    price: 980,
    image: "https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=400&h=400&fit=crop",
    description:
      "A5 hardcover notebook with a vintage typewriter-inspired cover design. 160 pages of 120gsm cream paper, lay-flat binding.",
    badge: "new",
    tags: ["premium"],
    rating: 4.8,
    reviewCount: 34,
    inStock: true,
    brand: "Inkwell Original",
    sku: "INK-NB-080",
    unit: "Piece",
    stock: 28,
  },
  {
    id: "na-003",
    slug: "metallic-gel-pen-collection",
    name: "Metallic Gel Pen Collection",
    category: "Pens",
    categorySlug: "pens",
    price: 720,
    image: "https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=400&h=400&fit=crop",
    description:
      "Set of 10 metallic gel pens with shimmering ink. Perfect for card-making, journaling, and decorative writing.",
    badge: "new",
    tags: ["art", "colorful"],
    rating: 4.6,
    reviewCount: 27,
    inStock: true,
    brand: "Sakura Art",
    sku: "SAK-PN-030",
    unit: "Set",
    stock: 18,
  },
  {
    id: "na-004",
    slug: "acrylic-paint-marker-set",
    name: "Acrylic Paint Marker Set",
    category: "Art Supplies",
    categorySlug: "art-supplies",
    price: 1650,
    image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&h=400&fit=crop",
    description:
      "Water-based acrylic paint markers in 12 bold colors. Medium 2mm tip, opaque coverage on most surfaces.",
    badge: "new",
    tags: ["art", "premium"],
    rating: 4.5,
    reviewCount: 15,
    inStock: true,
    brand: "ArtLine Pro",
    sku: "ALP-AS-080",
    unit: "Set",
    stock: 14,
  },
  {
    id: "na-005",
    slug: "recycled-paper-notepad",
    name: "Recycled Paper Notepad",
    category: "Paper",
    categorySlug: "paper",
    price: 290,
    image: "https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&h=400&fit=crop",
    description:
      "Eco-friendly A5 notepad made from 100% post-consumer recycled paper. 80 sheets, perforated pages, cardboard backing.",
    badge: "new",
    tags: ["minimal"],
    rating: 4.3,
    reviewCount: 9,
    inStock: true,
    brand: "Inkwell Original",
    sku: "INK-PP-080",
    unit: "Piece",
    stock: 5,
  },
  {
    id: "na-006",
    slug: "cable-management-clips",
    name: "Cable Management Clips",
    category: "Office Supplies",
    categorySlug: "office-supplies",
    price: 350,
    image: "https://images.unsplash.com/photo-1589582754973-0d6a8d4ab790?w=400&h=400&fit=crop",
    description:
      "Set of 12 adhesive cable clips in 3 sizes. Keeps desk cables organized and tangle-free. Strong 3M adhesive backing.",
    badge: "new",
    tags: ["office"],
    rating: 4.1,
    reviewCount: 12,
    inStock: true,
    brand: "Inkwell Original",
    sku: "INK-OS-080",
    unit: "Pack",
    stock: 35,
  },
];

// Derived arrays for homepage sections (keep existing section imports working)
export const featuredProducts = allProducts.filter((p) =>
  ["fp-001", "fp-002", "fp-003", "fp-004", "fp-005", "fp-006"].includes(p.id),
);
export const bestSellingWeekly = allProducts.filter((p) =>
  ["bsw-001", "bsw-002", "bsw-003", "bsw-004", "bsw-005", "bsw-006"].includes(p.id),
);
export const bestSellingMonthly = allProducts.filter((p) =>
  ["bsm-001", "bsm-002", "bsm-003", "bsm-004", "bsm-005", "bsm-006"].includes(p.id),
);
export const newArrivals = allProducts.filter((p) =>
  ["na-001", "na-002", "na-003", "na-004", "na-005", "na-006"].includes(p.id),
);
