import type { Review } from "@/lib/types/review";

export const reviews: Review[] = [
  {
    id: "rev-001",
    productId: "fp-001",
    productName: "Midnight Velvet Journal",
    customerId: "cust-001",
    customerName: "Tanvir Hasan",
    rating: 5,
    comment: "Absolutely gorgeous journal! The velvet cover feels premium and the paper quality is outstanding. No bleed-through with my fountain pens. Will buy again.",
    createdAt: "2026-06-20T10:30:00Z",
  },
  {
    id: "rev-002",
    productId: "fp-002",
    productName: "Sakura Brush Pen Set (12pc)",
    customerId: "cust-002",
    customerName: "Sabrina Ahmed",
    rating: 5,
    comment: "These brush pens are incredible for calligraphy practice. The ink flow is smooth and the flexible tips give beautiful thick-thin variation. Best set I've owned.",
    createdAt: "2026-06-25T14:15:00Z",
  },
  {
    id: "rev-003",
    productId: "fp-004",
    productName: "Desk Organizer Bamboo Set",
    customerId: "cust-003",
    customerName: "Rafiq Uddin",
    rating: 4,
    comment: "Good quality bamboo and looks great on my desk. Only reason for 4 stars is that one compartment is slightly smaller than I expected. Otherwise perfect for organizing pens, scissors, and sticky notes.",
    createdAt: "2026-06-28T09:00:00Z",
  },
  {
    id: "rev-004",
    productId: "bsw-001",
    productName: "College Ruled Spiral Notebook",
    customerId: "cust-007",
    customerName: "Mehedi Rahman",
    rating: 5,
    comment: "My go-to notebook for university classes. The pages are thick enough for gel pens and the spiral binding stays flat. Great value for the price.",
    createdAt: "2026-07-02T11:45:00Z",
  },
  {
    id: "rev-005",
    productId: "fp-005",
    productName: "Watercolor Pan Palette (24 Colors)",
    customerId: "cust-006",
    customerName: "Farhana Begum",
    rating: 4,
    comment: "Beautiful color range and the pigments are quite vibrant for a student-grade set. The tin is compact and portable. A few colors are a bit chalky but overall very satisfied.",
    createdAt: "2026-07-05T16:30:00Z",
  },
  {
    id: "rev-006",
    productId: "bsm-001",
    productName: "Leather Bound Diary 2026",
    customerId: "cust-004",
    customerName: "Nusrat Jahan",
    rating: 5,
    comment: "The leather quality is beautiful and it smells amazing. Layout is perfect for my daily planning. The ribbon bookmark is a nice touch. A bit pricey but worth every taka.",
    createdAt: "2026-07-03T08:20:00Z",
  },
  {
    id: "rev-007",
    productId: "bsw-006",
    productName: "Wax Crayons (32 colors)",
    customerId: "cust-010",
    customerName: "Afia Naznin",
    rating: 3,
    comment: "Decent crayons for kids but the color payoff on dark paper is poor. My 5-year-old enjoys them though. The box could be sturdier - it ripped during delivery.",
    createdAt: "2026-07-06T13:00:00Z",
  },
  {
    id: "rev-008",
    productId: "bsw-003",
    productName: "Fine Liner Drawing Pens",
    customerId: "cust-009",
    customerName: "Sakib Chowdhury",
    rating: 5,
    comment: "Professional quality at an affordable price. The ink is truly waterproof once dry and the tips are incredibly precise. Perfect for my architectural sketches.",
    createdAt: "2026-07-07T10:10:00Z",
  },
  {
    id: "rev-009",
    productId: "na-002",
    productName: "Vintage Typewriter Notebook",
    customerId: "cust-008",
    customerName: "Tasnim Fariha",
    rating: 2,
    comment: "The cover design is beautiful but the pages are too smooth for my fountain pen - the ink takes forever to dry and smudges easily. Disappointed with the paper quality inside.",
    createdAt: "2026-07-08T15:45:00Z",
  },
  {
    id: "rev-010",
    productId: "bsm-005",
    productName: "Exercise Book Bundle (10pc)",
    customerId: "cust-001",
    customerName: "Tanvir Hasan",
    rating: 4,
    comment: "Great for school use. Bought these for my younger siblings and they lasted the whole term. Pages are decent quality and the covers are colorful. Only wish they had more pages per book.",
    createdAt: "2026-07-10T09:30:00Z",
  },
];
